<?php

use Drupal\Core\Routing\RouteMatchInterface;

function good_habits_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.good_habits':
            $output = '<p>This is the help</p>';

            return $output;
    }
}

function good_habits_theme($existing, $type, $theme, $path)
{
    return [
        'good_habits' => [
            'variables' => [
                't' => NULL,
            ],
            'template' => 'good_habits',
        ],
        'hello' => [
            'template'  => 'hello',
            'variables' => []
        ]
    ];
}
