<?php

use Drupal\Core\Routing\RouteMatchInterface;

function goblacm_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.goblac':
            $output = '<p>This is the help</p>';

            return $output;
    }
}

function goblacm_theme($existing, $type, $theme, $path)
{
    return [
        'goblac_hello' => [
            'template'  => 'hello',
            'variables' => []
        ],
        'gb_thanks_for_sharing' => [
            'template' => 'thanks_for_sharing',
            'variables' => [
                'main_msg'  => 'teste',
                'sub_msg'   => 'teste_2',
                'directs_to' => 'home',
                'label'     => 'teste_botao',
                'img_path'  => 't',
            ],
        ],
    ];
}
