<?php

/**
 * @file
 */

use Drupal\Component\Utility\Xss;
use Drupal\Component\Utility\Html;

/**
 * Add dynamic library definitions.
 *
 * Modules may implement this hook to add dynamic library definitions. Static
 * libraries, which do not depend on any runtime information, should be declared
 * in a modulename.libraries.yml file instead.
 *
 * @return array[]
 *   An array of library definitions to register, keyed by library ID. The
 *   library ID will be prefixed with the module name automatically.
 *
 * @see core.libraries.yml
 * @see hook_library_info_alter()
 */
function goblac_adaptive_library_info_build() {
  $libraries = [];
  $theme = 'goblac_adaptive';
  $theme_registry = \Drupal::service('theme.registry')->get();
  $config = \Drupal::config($theme . '.settings')->get('settings');

  // Layout libraries.
  $libraries[$theme . '.layout.page'] = [
    'css' => [
      'layout' => [
        'styles/css/generated/' . $theme . '.layout.page.css' => [],
      ],
    ],
  ];
  foreach ($theme_registry as $key => $values) {
    if (substr($key, 0, 6) == 'page__') {
      $suggestion = str_replace('_', '-', $key);
      $libraries[$theme . '.layout.' . $key] = [
        'css' => [
          'layout' => [
            'styles/css/generated/' . $theme . '.layout.' . $suggestion . '.css' => [],
          ],
        ],
      ];
    }
  }

  // Extension libraries.
  if (isset($config['enable_extensions']) && $config['enable_extensions'] === 1) {
    // Fonts.
    if (isset($config['enable_fonts']) && $config['enable_fonts'] === 1) {
      // Google fonts.
      if (!empty($config['font_google'])) {
        $libraries['google_fonts'] = [
          'remote' => 'https://fonts.google.com',
          'license' => [
            'name' => 'SIL (OFL)',
            'url' => 'http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL',
            'gpl-compatible' => TRUE,
          ],
          'css' => [
            'base' => [
              Xss::filter($config['font_google']) => [],
            ],
          ],
          'weight' => -1000,
        ];
      }
      // Typekit.
      if (!empty($config['font_typekit'])) {
        $libraries['typekit_id'] = [
          'remote' => '//use.typekit.net/',
          'license' => [
            'name' => 'Apache 2.0',
            'url' => 'http://www.apache.org/licenses/LICENSE-2.0',
            'gpl-compatible' => TRUE,
          ],
          'js' => [
            '//use.typekit.net/' . Html::escape($config['font_typekit']) . '.js' => ['type' => 'external'],
          ],
          'header' => TRUE,
        ];
      }
    }
  }

  return $libraries;
}

/**
 * Alter attachments (typically assets) to a page before it is rendered.
 *
 * Use this hook when you want to remove or alter attachments on the page, or
 * add attachments to the page that depend on another module's attachments (this
 * hook runs after hook_page_attachments().
 *
 * @param array &$page
 *   An empty renderable array representing the page.
 *
 * @see hook_page_attachments_alter()
 */
function goblac_adaptive_page_attachments_alter(array &$page) {
  $theme = 'goblac_adaptive';

  // Attach module dependant libraries.
  // These libraries are declared in your STARTERKIT.libraries.yml and we only
  // load if the module is installed.
  $module_libraries = [
    'addtoany',
    'ds',
    'social_media_links',
    'superfish',
  ];
  $theme_libraries = \Drupal::service('library.discovery')->getLibrariesByExtension($theme);
  foreach ($module_libraries as $module_library) {
    if (array_key_exists($module_library, $theme_libraries) && \Drupal::moduleHandler()->moduleExists($module_library) === TRUE) {
      $page['#attached']['library'][] = "$theme/$module_library";
    }
  }
}

/**
 * Preprocess variables for html templates.
 */
/* -- Delete this line if you want to use this function
function goblac_adaptive_preprocess_html(&$variables) {
}
// */

/**
 * Preprocess variables for page templates.
 */
function goblac_adaptive_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'goblac_adaptive/fontawesome';
}

/**
 * Preprocess variables for field templates.
 */
/* -- Delete this line if you want to use this function
function goblac_adaptive_preprocess_field(&$variables) {
}
// */

/**
 * Preprocess variables for node templates.
 */
/* -- Delete this line if you want to use this function
function goblac_adaptive_preprocess_node(&$variables) {
}
// */

/**
 * Preprocess variables for comment templates.
 */
/* -- Delete this line if you want to use this function
function goblac_adaptive_preprocess_comment(&$variables) {
}
// */

/**
 * Preprocess variables for block templates.
 */
/* -- Delete this line if you want to use this function
function goblac_adaptive_preprocess_block(&$variables) {
}
// */

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function goblac_adaptive_preprocess_block__bundle__complex_banner(&$variables) {
    $config = \Drupal::config('system.site');
    $variables['content']['site_name'] = $config->get('name');
}

function goblac_adaptive_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#id']) && $variables['elements']['#id'] == 'goblac_adaptive_estrategiasyretosenamericalatinayelcaribe') {
    $variables['elements']['img_align'] = $variables['elements']['content']['field_ifs_image_alignment'][0]['#markup'] ? 'content-left' : 'content-right';

    $variables['elements']['text_align'] = $variables['elements']['content']['field_ifs_image_alignment'][0]['#markup'] ? 'content-right' : 'content-left';

    //dump($variables);
    }

  }

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function goblac_adaptive_preprocess_block__bundle__info_section(&$variables) {
    $is_img_position_left = $variables['elements']['content']['field_ifs_image_alignment'][0]['#markup'] == "Left"; 
    $is_text_color_scheme_dark = $variables['content']['field_ifs_text_color_scheme'][0]['#markup'] == 'Dark';

    $variables['elements']['img_align'] = $is_img_position_left ? 'content-left' : 'content-right';

    $variables['elements']['text_align'] = $is_img_position_left ? 'content-right' : 'content-left';

    $flex_row_direction = $is_img_position_left ?  'flex-row-reverse' : '';

    $variables['content_attributes']['class'] = $flex_row_direction;

    $variables['elements']['text_color_scheme'] = $is_text_color_scheme_dark ? 'text-dark' : 'text-light';

    //dump($variables);
}

function goblac_adaptive_preprocess_block__block_group__good_habits_search_block(&$variables) {
  $variables['content']['banner_title'] = t('Repositorio de buenas prácticas');
  $variables['content']['banner_summary'] = t('Encuentra Buenas Prácticas y Herramientas desarrolladas en la región');
}

function goblac_adaptive_preprocess_field__node__field_gh_image_roll(&$variables) {
  $items_length = count($variables['items']);
  $grid_placeholder = '<div></div>';

  if ($items_length == 3) {
    $variables['items'][3] = $variables['items'][2];
    $variables['items'][2] = $variables['items'][1];
    $variables['items'][1] = $variables['items'][0];

    $variables['items'][0] = $grid_placeholder;
    $variables['items'][4] = $grid_placeholder;
  } elseif ($items_length == 4) {
    $variables['items'][4] = $grid_placeholder;
  } else {}
}

function goblac_adaptive_form_node_good_habits_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  $form['actions']['submit']['#value'] = t('Enviar para aprobación');
}